//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenhNhan_DiUng
    {
        public int idBenhNhan { get; set; }
        public int idDiUng { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual DiUng DiUng { get; set; }
    }
}
