//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaKham()
        {
            this.LichKhams = new HashSet<LichKham>();
        }
    
        public int MaCaKham { get; set; }
        public Nullable<int> idBS { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<int> MaKhungGio { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual KhungGio KhungGio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichKham> LichKhams { get; set; }
    }
}
