//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaBacSi
    {
        public int idDanhGia { get; set; }
        public Nullable<int> idBacSi { get; set; }
        public Nullable<int> idBenhNhan { get; set; }
        public Nullable<double> diemDanhGia { get; set; }
        public string binhLuan { get; set; }
        public Nullable<System.DateTime> ngayDanhGia { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
    }
}
