//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public int MaDonThuoc { get; set; }
        public Nullable<int> MaLichKham { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayKeDon { get; set; }
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string LieuLuong { get; set; }
        public Nullable<int> MaCaKham { get; set; }
    
        public virtual CaKham CaKham { get; set; }
        public virtual LichKham LichKham { get; set; }
    }
}
