//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichKham()
        {
            this.DonThuocs = new HashSet<DonThuoc>();
        }
    
        public int MaLichKham { get; set; }
        public Nullable<int> MaBenhNhan { get; set; }
        public Nullable<int> MaCaKham { get; set; }
        public Nullable<System.DateTime> NgayDatLich { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual CaKham CaKham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuoc> DonThuocs { get; set; }
    }
}
