//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatLichKhamBenh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienSuBenh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TienSuBenh()
        {
            this.BenhNhan_TienSuBenh = new HashSet<BenhNhan_TienSuBenh>();
        }
    
        public int idTienSuBenh { get; set; }
        public string tenTSB { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenhNhan_TienSuBenh> BenhNhan_TienSuBenh { get; set; }
    }
}
